### ISSUE TITLE
Continuous integration tests to lint and test configurations

### ISSUE THREAD

**Issue by erictleung** [erictleung/dotfiles#18]
Shell scripts: https://carlosbecker.com/posts/lint-shell-scripts/ and https://github.com/koalaman/shellcheck

Vim: https://github.com/syngan/vim-vimlint

**Comment by erictleung** [comment]
Multiple settings example

```
matrix:
  include:
    - language: ruby
      rvm: 2.2
      before_script: gem install awesome_bot
      script: awesome_bot --allow-redirect --alow-ssl README.md

    - language: node_js
      node_js: 'node'
      before_script: npm install awesome-lint

notifications:
  email: false   
```
